spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audit_log
    username: audit
    password: audit
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
